packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  - 'components/**'
  - 'build/**'
  - 'play/**'
  # exclude packages that are inside test directories
  - '!**/test/**'